replicas:
  webfront1:
    replicaCount: 1
  webfront2:
    replicaCount: 1
  mysqlsrv:
    replicaCount: 1
  internalsvc:
    replicaCount: 1

resources: {}

image:
  webfront1:
    repository: docker.io/sarroutbi
    name: webfront1
    tag: sergioarroutbibraojos
    pullPolicy: Always
  webfront2:
    repository: docker.io/sarroutbi
    name: webfront2
    tag: sergioarroutbibraojos
    pullPolicy: Always
  mysqlsrv:
    repository: docker.io/sarroutbi
    name: mysqlsrv
    tag: sergioarroutbibraojos
    pullPolicy: Always
  internalsvc:
    repository: docker.io/sarroutbi
    name: internalsvc
    tag: sergioarroutbibraojos
    pullPolicy: Always

service:
  webfront:
    name: webfront
    type: ClusterIP
    port: 8443
    hazelcast:
      port: 5701
  webfront1:
    name: webfront1
    type: ClusterIP
    port: 8443
    hazelcast:
      port: 5701
  webfront2:
    name: webfront2
    type: ClusterIP
    port: 8443
    hazelcast:
      port: 5701
  mysqlsrv:
    name: mysqlsrv
    type: ClusterIP
    port: 3306
  internalsvc:
    name: internalsvc
    type: ClusterIP
    port: 8443

ingress:
  class: nginx
  name: guardarpunto-ingress
  backend:
    protocol: HTTPS
  host:
    name: guardarpunto.example.com
  secret:
    name: guardarpunto-tls-cert
  path: "/*"
env:
  logLevel: 6
  # TBD
