replicas:
  webfront1:
    replicaCount: 1
  webfront2:
    replicaCount: 1

resources: {}

image:
  webfront1:
    repository: docker.io/sarroutbi
    name: webfront1
    tag: latest
    pullPolicy: Always
  webfront2:
    repository: docker.io/sarroutbi
    name: webfront2
    tag: latest
    pullPolicy: Always

service:
  webfront1:
    name: webfront1
    type: ClusterIP
    port: 8443
  webfront2:
    name: webfront2
    type: ClusterIP
    port: 8443

env:
  logLevel: 6
  # TBD
