replicas:
  webfront1:
    replicaCount: 1
  webfront2:
    replicaCount: 1
  mysqlsrv:
    replicaCount: 1
  internalsvc:
    replicaCount: 1

resources: {}

image:
  webfront1:
    repository: docker.io/sarroutbi
    name: webfront1
    tag: latest
    pullPolicy: Always
  webfront2:
    repository: docker.io/sarroutbi
    name: webfront2
    tag: latest
    pullPolicy: Always
  mysqlsrv:
    repository: docker.io/sarroutbi
    name: mysqlsrv
    tag: latest
    pullPolicy: Always
  internalsvc:
    repository: docker.io/sarroutbi
    name: internalsvc
    tag: latest
    pullPolicy: Always

service:
  webfront1:
    name: webfront1
    type: ClusterIP
    port: 8443
    hazelcast:
      port: 5701
  webfront2:
    name: webfront2
    type: ClusterIP
    port: 8443
    hazelcast:
      port: 5701
  mysqlsrv:
    name: mysqlsrv
    type: ClusterIP
    port: 3306
  internalsvc:
    name: internalsvc
    type: ClusterIP
    port: 8443

env:
  logLevel: 6
  # TBD
