apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.pvolume.name }}
  labels:
    type: {{ .Values.pv.pvolume.type }}
spec:
  storageClassName: {{ .Values.pv.pvolume.storageClassName }}
  capacity:
    storage: {{ .Values.pv.pvolume.capacity }}
  accessModes:
    - {{ .Values.pv.pvolume.accessMode }}
  hostPath:
    path: {{ .Values.pv.pvolume.hostPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pv.pvolumeclaim.name }}
spec:
  storageClassName: {{ .Values.pv.pvolumeclaim.storageClassName }}
  accessModes:
    - {{ .Values.pv.pvolumeclaim.accessMode }}
  resources:
    requests:
      storage: {{ .Values.pv.pvolumeclaim.request.storage }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.service.webfront1.name }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  replicas: {{ .Values.replicas.webfront1.replicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.service.webfront.name }}
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.webfront1.repository }}/{{ .Values.image.webfront1.name }}:{{ .Values.image.webfront1.tag }}
        imagePullPolicy: {{ .Values.image.webfront1.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.webfront1.port }}
        env:
        - name: LOGLEVEL
          value: {{ .Values.env.logLevel | quote}}
        resources:
{{ toYaml .Values.resources | indent 10 }}
      restartPolicy: Always
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.service.webfront2.name }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  replicas: {{ .Values.replicas.webfront2.replicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.service.webfront.name }}
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.webfront2.repository }}/{{ .Values.image.webfront2.name }}:{{ .Values.image.webfront2.tag }}
        imagePullPolicy: {{ .Values.image.webfront2.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.webfront2.port }}
        env:
        - name: LOGLEVEL
          value: {{ .Values.env.logLevel | quote}}
        resources:
{{ toYaml .Values.resources | indent 10 }}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.webfront.name }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  type: {{ .Values.service.webfront.type }}
  ports:
  - name: http-spring
    port: {{ .Values.service.webfront.port }}
  - name: hazelcast
    port: {{ .Values.service.webfront1.hazelcast.port }}
    targetPort: {{ .Values.service.webfront1.hazelcast.port }}
  selector:
    app: {{ .Values.service.webfront.name }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.service.mysqlsrv.name }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  replicas: {{ .Values.replicas.mysqlsrv.replicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.service.mysqlsrv.name }}
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      volumes:
      - name: {{ .Values.pv.vol.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.pv.pvolumeclaim.name }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.mysqlsrv.repository }}/{{ .Values.image.mysqlsrv.name }}:{{ .Values.image.mysqlsrv.tag }}
        imagePullPolicy: {{ .Values.image.mysqlsrv.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.mysqlsrv.port }}
        volumeMounts:
          - mountPath: {{ .Values.pv.vol.volumeMounts.mountPath }}
            name: {{ .Values.pv.vol.name }}
        env:
        - name: LOGLEVEL
          value: {{ .Values.env.logLevel | quote}}
        resources:
{{ toYaml .Values.resources | indent 10 }}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.mysqlsrv.name }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  type: {{ .Values.service.mysqlsrv.type }}
  ports:
  - name: mysql-port
    port: {{ .Values.service.mysqlsrv.port }}
    targetPort: {{ .Values.service.mysqlsrv.port }}
  selector:
    app: {{ .Values.service.mysqlsrv.name }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.service.internalsvc.name }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  replicas: {{ .Values.replicas.internalsvc.replicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.service.internalsvc.name }}
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.internalsvc.repository }}/{{ .Values.image.internalsvc.name }}:{{ .Values.image.internalsvc.tag }}
        imagePullPolicy: {{ .Values.image.internalsvc.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalsvc.port }}
        env:
        - name: LOGLEVEL
          value: {{ .Values.env.logLevel | quote}}
        resources:
{{ toYaml .Values.resources | indent 10 }}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.internalsvc.name }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  type: {{ .Values.service.internalsvc.type }}
  ports:
  - name: http-spring
    port: {{ .Values.service.internalsvc.port }}
  selector:
    app: {{ .Values.service.internalsvc.name }}
