apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/backend-protocol: {{ .Values.ingress.backend.protocol }}
spec:
  tls:
    - hosts:
      - {{ .Values.ingress.host.name }}
      secretName: {{ .Values.ingress.secret.name }}
  rules:
  - host: {{ .Values.ingress.host.name }}
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        backend:
          serviceName: {{ .Values.service.webfront.name }}
          servicePort: {{ .Values.service.webfront.port }}
