apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: guardarpunto-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  tls:
    - hosts:
      - guardarpunto.example.com
      secretName: guardarpunto-tls-cert
  rules:
  - host: guardarpunto.example.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: webfront1
          servicePort: 8443
      - path: /*
        backend:
          serviceName: webfront2
          servicePort: 8443
