apiVersion: extensions/v1beta1  
kind: Ingress  
metadata:  
  name: guardarpunto
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
spec:
  tls:
  - hosts:
    - guardarpunto.example.com
    secretName: guardarpunto-tls-cert
  rules:
    - host: guardarpunto.example.com
      http:
        paths:
        - path: /*
          backend:
            serviceName: webfront1
            servicePort: 8443
